
services:
  app-1:
    build: ./app-1
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  app-2:
    build: ./app-2
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default
