# helm/app-2/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-2.fullname" . }}
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: {{ include "app-2.name" . }}
