name: Deploy app-2 to Kubernetes

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build and Package with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Image for app-2
        run: docker build -t <dockerhub-username>/app-2 ./app-2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image for app-2 to DockerHub
        run: docker push <dockerhub-username>/app-2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: actions/setup-kubectl@v2
        with:
          kubectl-version: 'v1.21.0'

      - name: Set up kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy app-2 to Kubernetes using Helm
        run: |
          helm upgrade --install app-2 ./helm/app-2 --set image.repository=<dockerhub-username>/app-2 --set image.tag=latest
