apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
        - name: app-2
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/app-2:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: app-2-service
spec:
  selector:
    app: app-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer
