name: Deploy app-1 to GKE

on:
  push:
    branches:
      - main  # Or specify a branch for triggering

jobs:
  build-and-deploy-app-1:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up GCP credentials for authentication
      - name: Set up GCP credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Docker to push images to Google Container Registry (GCR)
      - name: Configure Docker to use GCP
        run: |
          gcloud auth configure-docker gcr.io

      # Build Docker image for app-1
      - name: Build Docker image for app-1
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/app-1:${{ github.sha }} ./app-1

      # Push Docker image to GCR
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/app-1:${{ github.sha }}

      # Set up kubectl for interacting with GKE
      - name: Set up kubectl
        uses: google-github-actions/setup-kubectl@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_ZONE }}

      # Deploy app-1 to GKE
      - name: Deploy app-1 to GKE
        run: |
          kubectl apply -f k8s/app-1-deployment.yaml
          kubectl apply -f k8s/app-1-service.yaml

      # Verify the deployment
      - name: Verify app-1 deployment
        run: |
          kubectl get pods
          kubectl get svc
